stages:
    - build
    - deploy

variables:
 DOCKER_HOST: "tcp://localhost:2375"
 DOCKER_REGISTRY: "docker-hub.informatik.haw-hamburg.de"
 NEXUS_REGISTRY: "nexus.informatik.haw-hamburg.de"
 SERVICE_NAME: "wp-mbc-ss2018/who-squares"

build_image:
  stage: build
  image: nexus.informatik.haw-hamburg.de/docker:stable-dind
  script:
   # Einloggen in HAW Registries
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
   - docker login -u $NEXUS_USER -p $NEXUS_PW $NEXUS_REGISTRY
   # Bauen...
   - docker build -t $SERVICE_NAME:latest .
   - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_PIPELINE_ID
   - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:latest
   - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_PIPELINE_ID
   - docker push $DOCKER_REGISTRY/$SERVICE_NAME:latest
  only:
  - master
  - icc

# Triggered das Deployment
deploy:
  environment:
    name: ICC-K8s
  stage: deploy
  image: nexus.informatik.haw-hamburg.de/kubectl:v1.10.3
  script:
    #
    - cp kubernetes_deployment.yaml kubernetes_deployment_new.yaml
    - sed -i "s/wp-mbc-ss2018\/who-squares:latest/wp-mbc-ss2018\/who-squares:${CI_PIPELINE_ID}/g" kubernetes_deployment_new.yaml
    # Deploy files
    - kubectl apply -f kubernetes_deployment_new.yaml